### ISSUE TITLE
brew update: Please report this to the fraction/formulae tap!

### ISSUE THREAD

**Issue by scherii** [fraction/sshcd#16]
When I run `brew update` it warns me about this:

```
Warning: Calling GithubGistFormula.url is deprecated!
Use Formula.url instead.
/usr/local/Homebrew/Library/Taps/fraction/homebrew-formulae/sshcd.rb:5:in `<class:Sshcd>'
Please report this to the fraction/formulae tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/fraction/homebrew-formulae/sshcd.rb:6:in `<class:Sshcd>'
Please report this to the fraction/formulae tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/fraction/homebrew-formulae/sshcd.rb:6:in `<class:Sshcd>'
Please report this to the fraction/formulae tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/fraction/homebrew-formulae/sshcd.rb:6:in `<class:Sshcd>'
Please report this to the fraction/formulae tap!
```

**Comment by christianbundy** [comment]
Sorry I've left this for so long. I don't use Homebrew anymore (or macOS -- I'm all Linux now) so I'd merge a fix for this in my formulae repo, but I don't think that I'll have capacity to resolve this.

**Comment by tony13tv** [comment]
Hi @christianbundy would you consider to tranfer the repo to anyone who would want to continue with your work.

**Comment by christianbundy** [comment]
I'd be happy to merge any pull requests to resolve this problem, but I don't think I'd like to transfer the repo. Please feel free to copy the repository, contribute patches, or both.
